# Generated by Django 6.0.2 on 2026-02-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_mpesapayments_systemsettings_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admins',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admins',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admins',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
