# Generated by Django 6.0.2 on 2026-02-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_admins_created_at_alter_loans_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='loan_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='loan_reason_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='county',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='town',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='village',
            field=models.TextField(blank=True, null=True),
        ),
    ]
