# Generated by Django 6.0.2 on 2026-02-10 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_admins_id_alter_auditlogs_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_loans', to='apps.admins'),
        ),
        migrations.AddField(
            model_name='users',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_users', to='apps.admins'),
        ),
    ]
