# Generated by Django 6.0.2 on 2026-02-10 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_loans_created_by_users_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='status',
            field=models.TextField(default='UNVERIFIED'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='apps.users'),
        ),
    ]
