# Generated by Django 6.0.2 on 2026-02-10 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_admins_region_alter_loans_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.admins')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='apps.loans')),
            ],
            options={
                'db_table': 'loan_activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LoanDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('file_path', models.TextField()),
                ('doc_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='apps.loans')),
            ],
            options={
                'db_table': 'loan_documents',
                'managed': True,
            },
        ),
    ]
