# Generated by Django 6.0.2 on 2026-02-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_loanactivity_loandocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='admins',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='base_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
